on: [push, pull_request]

name: CI

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.73.0
      - name: cargo clippy
        run: cargo clippy -p svgbobdoc --all-features

  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.73.0
      - name: cargo test
        run: cargo test -p svgbobdoc
      - name: cargo test with `enable`
        run: cargo test -p svgbobdoc --features enable
